version: 0.2

phases:
  pre_build:
    commands:
      - echo Building env vars
      - echo -e "REACT_APP_BUILD_DATE=\"$(date)\"\nREACT_APP_BUILD_COMMIT=\"$(git rev-parse HEAD)\"" > .env
  build:
    commands:
      - npm install
      - npm run build
artifacts:
  files:
    - '**/*'
  base-directory: build
